input_max_length: 131072,131072,131072
datasets: narrativeqa_130772,infbench_qa_eng_130862,infbench_choice_eng_130862
generation_max_length: 100,10,10
test_files: ',,'
demo_files: ',,'
use_chat_template: true
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
