input_max_length: '131072'
datasets: msmarco_rerank_psg
generation_max_length: '200'
test_files: data/msmarco/test_reranking_data_k1000_dep3.jsonl
demo_files: data/msmarco/test_reranking_data_k10_dep3.jsonl
use_chat_template: false
max_test_samples: 100
shots: 2
stop_new_line: true
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
