input_max_length: 131072,131072,131072,131072,131072,131072,131072,131072,131072,131072,131072,131072,131072
datasets: ruler_niah_s_1,ruler_niah_s_2,ruler_niah_s_3,ruler_niah_mk_1,ruler_niah_mk_2,ruler_niah_mk_3,ruler_niah_mq,ruler_niah_mv,ruler_cwe,ruler_fwe,ruler_vt,ruler_qa_1,ruler_qa_2
generation_max_length: 50,50,50,50,50,100,100,50,100,50,50,50,50
test_files: data/ruler/niah_single_1/validation_131072.jsonl,data/ruler/niah_single_2/validation_131072.jsonl,data/ruler/niah_single_3/validation_131072.jsonl,data/ruler/niah_multikey_1/validation_131072.jsonl,data/ruler/niah_multikey_2/validation_131072.jsonl,data/ruler/niah_multikey_3/validation_131072.jsonl,data/ruler/niah_multiquery/validation_131072.jsonl,data/ruler/niah_multivalue/validation_131072.jsonl,data/ruler/cwe/validation_131072.jsonl,data/ruler/fwe/validation_131072.jsonl,data/ruler/vt/validation_131072.jsonl,data/ruler/qa_1/validation_131072.jsonl,data/ruler/qa_2/validation_131072.jsonl
demo_files: ',,,,,,,,,,,,'
use_chat_template: false
max_test_samples: 100
shots: 0
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
