input_max_length: 131072,131072
datasets: infbench_sum_eng_129672,multi_lexsum_130372
generation_max_length: 1200,400
test_files: ','
demo_files: ','
use_chat_template: true
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
